### ISSUE TITLE
Question: how does the clock circuit work.

### ISSUE THREAD

**Issue by MichMich** [sqfmi/BTTF-BADGE#1]
First let me start by making a compliment about the beautiful pcb. I love it! And excuse me for "abusing" the GitHub issues for this question. 

I ordered the PCB as a fathers day present for my dad. I was studying the circuit to see how it works, and fail to grasp how the clock signal is generated:
![Screenshot 2020-06-09 at 13 33 32](https://user-images.githubusercontent.com/210954/84143016-200f3b80-aa56-11ea-87e5-66846b276b50.png)

I'm a beginner when it comes to analog circuits but very eager to learn. So hopefully you can shine a light on the black magic. :)

Thanks in advance!

**Comment by sqfmi** [comment]
Thanks @MichMich! That is very thoughtful, I'm sure your dad will love the gift 😄 Check out https://www.allaboutcircuits.com/technical-articles/exactly-how-schmitt-trigger-oscillators-work/ , it's a great article that explains how the oscillator works and how the frequency is calculated

**Comment by MichMich** [comment]
Ah! That was extremely helpful! Thanks for the link. And once again thanks for the nice design!
